services:
  jenkins:
    restart: always
    user: root
    image: jenkins/dockertest
    build:
      context: .
    ports:
      - 8081:8080
      - 50001:50000
    container_name: jenkinsdockertest
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
        #cambiar el volumen por la ruta local de la carpeta actual  + /jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_ADMIN_ID=${ENV_JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${ENV_JENKINS_ADMIN_PASSWORD}
    networks:
      - net
networks:
  net:
